### ISSUE TITLE
Request for Additional Program output (TIme Stamp)

### ISSUE THREAD

**Issue by willtco** [ray33ee/tenma-usb#1]
Looking good!  -   I'd like to request that a further command line option is added to include a stamp a time/date stamp after each printed string but on the same line  -T for time & date or -t for just time,  with some form of separator.   Secondly the option to   Overwrite as well as append thus a file may be only 1 line in length (but regularly updated) or multiple lines as in a Log.

**Comment by ray33ee** [comment]
Good idea! I've added the command line options to the to do list and it'll be part of the next release, I just need to consider how it will be done (I may add the option for users to specify their own data/time format) 

As for the second part, since the output is just sent to `stdout` the user can define how to use the output in their code. They can take the output and append it to a file, or overwrite the file with the output.

**Comment by ray33ee** [comment]
OK date/time stamp has been added in `0.1.3` (among other features, see changelog)
